"""Interview-transcript grading.

The Colab notebook ``video_interviews_transcriptions_grade_info_GEMINI`` does
not score keywords. It fills the auditor prompt (question + transcript) and
asks a model whether the answer is relevant, natural, and possibly an AI
script. ``audit_transcript`` does that through Ollama, which is the local model
this demo already runs.

``grade_transcript`` is the offline stand-in used while building the synthetic
cohort. It never reads the question. A random transcript has none of its
"off topic" words and a high unique-word ratio, so the stand-in scores it as a
strong answer. Do not use it on a live recording.
"""

import os
import re

from ..datagen.answers import LLM_TELL_WORDS
from .eligibility import extract_json_from_response

# The prompt shipped with the grading notebook. Placeholders are [Question]
# and [Interview Transcript].
AUDITOR_PROMPT = """# Role
You are an expert Interview Evaluator and Forensic Linguist. You specialize in analyzing video interview transcripts to assess communication skills and **detect the use of AI-generated scripts.**

# Task
Evaluate the provided interview transcript based on the one question asked.
You must critically assess if the student is speaking naturally or reading a pre-written response generated by an LLM (like ChatGPT).

# Input Data
**Question asked:**
[Question]

**Student Transcript:**
[Interview Transcript]

# Evaluation Criteria
Please analyze the response based on the following metrics:
1. **Relevance & Content:** Did they answer the question with specific, personal examples? If the transcript is gibberish, off topic, or does not address the question, relevance_score and overall_score must be low (relevance 1-3, overall under 35).
2. **Naturalness vs. Scripted:** Does the speech flow like a natural conversation, or does it sound like a read essay?
3. **AI Markers:** Look for "hallmark" LLM words (e.g., "delve," "underscore," "pivotal role," "tapestry") and overly perfect grammar lacking natural speech pauses.

# Output Format
You must output the result strictly as valid JSON. Do not include markdown formatting, intro text, or concluding remarks.

Use the following JSON schema:
{
  "overall_score": 0,
  "executive_summary": "",
  "ai_script_detection": {
    "is_likely_reading_llm_text": false,
    "suspicion_score": 0,
    "flags": [],
    "reasoning": ""
  },
  "metrics": {
    "relevance_score": 1,
    "clarity_score": 1,
    "structure_score": 1
  },
  "feedback": {
    "strengths": [],
    "areas_for_improvement": []
  }
}
"""

# Words that suggest a vague, low-effort answer.
_VAGUE = ("good", "important", "interesting", "try", "normal", "things", "stuff", "nice")
# Words that suggest the answer drifted off the question.
_OFF_TOPIC = ("campus", "football", "travel", "city", "cafeteria", "friend", "famous")


def _count_hits(text: str, words) -> int:
    low = text.lower()
    return sum(low.count(w) for w in words)


def grade_transcript(question: str, transcript: str) -> dict:
    """Return a grade dict in the auditor-notebook JSON shape."""
    words = transcript.split()
    n_words = max(1, len(words))
    unique_ratio = len(set(w.lower() for w in words)) / n_words

    tell_hits = _count_hits(transcript, LLM_TELL_WORDS)
    vague_hits = _count_hits(transcript, _VAGUE)
    off_hits = _count_hits(transcript, _OFF_TOPIC)

    # AI-script suspicion: driven by tell-words and unnaturally polished, low
    # repetition text.
    suspicion = min(100, tell_hits * 22 + (15 if unique_ratio > 0.75 else 0))
    is_scripted = suspicion >= 50

    # Sub-scores on a 1-10 scale.
    relevance = 9 - min(8, off_hits * 3) - min(4, vague_hits * 2)
    clarity = 4 + (3 if unique_ratio > 0.6 else 0) + (2 if n_words > 45 else 0) - min(2, vague_hits)
    structure = 3 + (4 if n_words > 60 else 1) + (2 if unique_ratio > 0.65 else 0)
    relevance = int(max(1, min(10, relevance)))
    clarity = int(max(1, min(10, clarity)))
    structure = int(max(1, min(10, structure)))

    # Overall 0-100, weighting relevance most. A scripted answer keeps decent
    # quality scores but is capped and penalised so it cannot reach the top band.
    overall = (0.5 * relevance + 0.25 * clarity + 0.25 * structure) / 10 * 100
    if is_scripted:
        overall = min(overall, 72) - suspicion * 0.12
    overall = int(max(0, min(100, round(overall))))

    flags = [w for w in LLM_TELL_WORDS if w in transcript.lower()]
    return {
        "overall_score": overall,
        "ai_script_detection": {
            "is_likely_reading_llm_text": is_scripted,
            "suspicion_score": int(suspicion),
            "flags": flags,
        },
        "metrics": {
            "relevance_score": relevance,
            "clarity_score": clarity,
            "structure_score": structure,
        },
        "backend": "heuristic",
        "model": "keyword-stand-in",
    }


def _clamp_int(value, low: int, high: int, default: int) -> int:
    try:
        number = int(round(float(value)))
    except (TypeError, ValueError):
        return default
    return max(low, min(high, number))


def normalize_audit(parsed: dict, *, backend: str, model: str) -> dict:
    """Keep the notebook's JSON shape and force scores into their legal ranges."""
    ai = parsed.get("ai_script_detection") or {}
    metrics = parsed.get("metrics") or {}
    flags = ai.get("flags") or []
    if not isinstance(flags, list):
        flags = [str(flags)]
    return {
        "overall_score": _clamp_int(parsed.get("overall_score"), 0, 100, 0),
        "executive_summary": str(parsed.get("executive_summary") or ""),
        "ai_script_detection": {
            "is_likely_reading_llm_text": bool(ai.get("is_likely_reading_llm_text")),
            "suspicion_score": _clamp_int(ai.get("suspicion_score"), 0, 100, 0),
            "flags": [str(flag) for flag in flags],
            "reasoning": str(ai.get("reasoning") or ""),
        },
        "metrics": {
            "relevance_score": _clamp_int(metrics.get("relevance_score"), 1, 10, 1),
            "clarity_score": _clamp_int(metrics.get("clarity_score"), 1, 10, 1),
            "structure_score": _clamp_int(metrics.get("structure_score"), 1, 10, 1),
        },
        "feedback": parsed.get("feedback") if isinstance(parsed.get("feedback"), dict) else {},
        "backend": backend,
        "model": model,
    }


def _preferred_grader_model() -> str | None:
    """A model the user named. None means 'whatever Ollama already has'."""
    named = os.environ.get("FAIRVID_GRADER_MODEL") or os.environ.get("FAIRVID_VLM_MODEL")
    return named.strip() if named else None


def _resolve_grader_model() -> str | None:
    from .vlm import _model_names, ollama_available
    named = _preferred_grader_model()
    if named:
        return named if ollama_available(named) else None
    if ollama_available("gemma3:4b"):
        return "gemma3:4b"
    try:
        import ollama
        names = _model_names(ollama.list())
    except Exception:
        return None
    return names[0] if names else None


def _ollama_audit(prompt: str) -> tuple[str, str]:
    from .vlm import _generate, _response_text, ollama_available
    model = _resolve_grader_model()
    if not model:
        raise RuntimeError("no Ollama model available for transcript grading")
    text = _response_text(_generate(model, prompt))
    # moondream answers images and returns nothing for a text grade.
    if not text and model.split(":")[0] == "moondream" and ollama_available("gemma3:1b"):
        model = "gemma3:1b"
        text = _response_text(_generate(model, prompt))
    if not text:
        raise RuntimeError(f"{model} returned an empty grade")
    return model, text


def audit_transcript(question: str, transcript: str, *, generate=None) -> dict:
    """Grade one live answer the way the notebook does.

    ``generate`` is a test hook: ``(prompt) -> (model_name, response_text)``.
    When it is omitted, Ollama is used if ``FAIRVID_GRADER`` is ``auto`` (the
    default) or ``ollama`` and the server answers. Any failure falls back to
    the keyword stand-in.
    """
    mode = os.environ.get("FAIRVID_GRADER", "auto").strip().lower()
    if generate is None and mode != "heuristic":
        try:
            if _resolve_grader_model() is not None:
                generate = _ollama_audit
        except Exception:
            generate = None
    if generate is not None and transcript.strip():
        prompt = (AUDITOR_PROMPT
                  .replace("[Question]", question or "(no question provided)")
                  .replace("[Interview Transcript]", transcript))
        failure = None
        try:
            model, raw = generate(prompt)
            ok, parsed = extract_json_from_response(raw)
            if ok and isinstance(parsed, dict) and "overall_score" in parsed:
                return normalize_audit(parsed, backend="ollama", model=model)
            failure = "Ollama replied, but the grade was not valid JSON"
        except Exception as exc:
            failure = str(exc)
    else:
        failure = None
    graded = grade_transcript(question, transcript)
    graded["backend"] = "heuristic"
    graded["model"] = "keyword-stand-in"
    if failure:
        graded["error"] = failure
    return graded
